[tool.poetry]
name = "sqlcache"
version = "0.1.0"
description = "Speed up your data analysis iterations with cached SQL queries"
authors = ["Felipe Aguirre Martinez <felipeam86@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.5"
sqlalchemy = "^1.3.22"
pyarrow = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
